<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="work\**" />
    <None Remove="work\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rover.Application\Rover.Application.csproj" />
    <ProjectReference Include="..\Rover.Infrastructure\Rover.Infrastructure.csproj" />
  </ItemGroup>
</Project>
